{
 "title": "QOS XRTP",
 "tags": [ "qos" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "MOS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "avg(heplify_xrtp_mos)", "legendFormat": "sipwise_pk" }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(heplify_xrtp_dle) > 0", "legendFormat": "sipwise_pk" }
   ]
  },
  {
   "title": "Received Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(heplify_xrtp_plr)", "legendFormat": "sipwise_pk" }
   ]
  },
  {
   "title": "Sent Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "avg(heplify_xrtp_pls)", "legendFormat": "sipwise_pk" }
   ]
  },
  {
   "title": "Received Jitter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(heplify_xrtp_jir)", "legendFormat": "sipwise_pk" }
   ]
  },
  {
   "title": "Sent Jitter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(heplify_xrtp_jis)", "legendFormat": "sipwise_pk" }
   ]
  },
  {
   "title": "Call Setup Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "avg(heplify_xrtp_cs) < 3600", "legendFormat": "sipwise_pk" }
   ]
  }
 ]
}