{
 "title": "SIP Calls & Registers",
 "tags": [ "sip" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tn",
    "label": "interface_name",
    "query": "label_values(heplify_method_response, target_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Concurrent Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"200\"}[5m]))) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[5m])) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[5m])) or sum(up) * 0)) * \n160 * sum(rate(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[5m]))",
     "legendFormat": "CS current"
    },
    {
     "expr": "(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"200\"}[5m] offset 1w))) / \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[5m] offset 1w)) - \n(sum(increase(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=~\"3.*|401|407\"}[5m] offset 1w)) or sum(up) * 0)) * \n160 * sum(rate(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[5m] offset 1w))",
     "legendFormat": "CS last week"
    }
   ]
  },
  {
   "title": "Calls per second & Call attempts per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"200\"}[5m]))",
     "legendFormat": "CPS per interface"
    },
    {
     "expr": "sum(rate(heplify_method_response{target_name=~\"$tn\", method=\"INVITE\", response=\"INVITE\"}[5m]))",
     "legendFormat": "CAPS per interface"
    }
   ]
  },
  {
   "title": "Register per second & Register attempts per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=\"200\"}[5m]))",
     "legendFormat": "RPS per interface"
    },
    {
     "expr": "sum(rate(heplify_method_response{target_name=~\"$tn\", method=\"REGISTER\", response=\"REGISTER\"}[5m]))",
     "legendFormat": "RAPS per interface"
    }
   ]
  }
 ]
}