{
 "title": "HOMER Stats",
 "tags": [ "qos" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "SIP Methods & Responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "stddev_over_time(heplify_method_response[$__interval]) by (method, response)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTCP Jitter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(heplify_rtcp_jitter[$__interval])",
     "legendFormat": "rtcp_jitter"
    }
   ]
  },
  {
   "title": "RTCP  Fraction Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(heplify_rtcp_fraction_lost[$__interval])",
     "legendFormat": "rtcp_fraction_lost"
    },
    {
     "expr": "avg_over_time(heplify_rtcpxr_fraction_lost[30m])",
     "legendFormat": "rtcpxr_fraction_lost"
    }
   ]
  },
  {
   "title": "RTCP  Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg_over_time(heplify_rtcp_packets_lost[$__interval])",
     "legendFormat": "rtcp_packets_lost"
    }
   ]
  },
  {
   "title": "RTCP DLSR",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg_over_time(heplify_rtcp_dlsr[$__interval])",
     "legendFormat": "rtcpxr_round_trip_delay"
    }
   ]
  }
 ]
}