server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/api/prom/push

scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
## Must allow port 1514:1514(/udp) in compose file
# - job_name: syslog
#   syslog:
#       listen_address: 0.0.0.0:1514
#       idle_timeout: 60s
#       label_structured_data: yes
#       labels:
#         job: "syslog"
#   relabel_configs:
#       - source_labels: ['__syslog_message_hostname']
#         target_label: 'host'
#       - source_labels: ['__syslog_message_app_name']
#         target_label: 'app'